ideal1 = input("insert ideal:")
body_part1 = input ("insert body part:")
noun1 = input ("insert noun:")
noun2 = input ("insert noun:")
adj1 = input ("insert adjective:")
verb1 = input ("insert a past tense verb:")
adj2 = input ("insert opposite adjective of last adjective:")
noun3 = input ("insert noun:")
adverb1 = input ("insert adverb:")
adj3 = input ("insert adjective:")
noun4 = input ("insert noun:")
verb2 = input ("insert verb:")
verb3 = input ("insert verb ending in ing:")
famous_website1 = input ("insert famous website:")
print("People say " + ideal1 + " is in the " + body_part1 + " of the beholder. I am here today demonstrate how true this " + noun1 + " is. Beauty is a " + noun2 + " that is completely subjective. Although I have always been " + adj1 + ", others have " + verb1 + " me " + adj2 + ". This alone proves my " + noun3 + ". " + adverb1 + ", society rarely accepts this " + adj3 + " " + noun4 + ". So more proof must be " + verb2 + ". If you are interested in " + verb3 + " more proofs, go to " + famous_website1 + ".")